Initialization time: 2025-05-26 12:08:42
wandb: Currently logged in as: maria-i-paiva (maria-i-paiva-inesc-tec) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250526_120943-ohd97n3h
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vgg16_25d_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc/runs/ohd97n3h
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 213, 1: 70
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 59, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
Error executing job with overrides: []
Traceback (most recent call last):
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 54, in run_hyperparameter_grid_based_execution_pipeline
    run_experiment_pipeline(config)
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 167, in run_experiment_pipeline
    model_pipeline.finalize()
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/model_pipeline.py", line 55, in finalize
    self.delete_model_checkpoints()
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/model_pipeline.py", line 48, in delete_model_checkpoints
    os.rmdir(
OSError: [Errno 39] Directory not empty: '/nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[1;34mwandb[0m: 
[1;34mwandb[0m: 🚀 View run [33mvgg16_25d_107_160_fold1[0m at: [34mhttps://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc/runs/ohd97n3h[0m
[1;34mwandb[0m: Find logs at: [1;35m../../experiment_results/experiment_107/version_160/wandb/run-20250526_120943-ohd97n3h/logs[0m
srun: error: 04.ctm-deep-05: task 0: Exited with exit code 1
wandb: Currently logged in as: maria-i-paiva (maria-i-paiva-inesc-tec) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250526_130958-w0af3qqm
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet50_25d_norm_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc/runs/w0af3qqm
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_1/models exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 213, 1: 70
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 59, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb: uploading config.yaml
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy █▃▆▂▄▁▃▃▄█▃▆▃▇▃▇▁█▁▄▆▂▄▄▇▇▅█▄▃▇▇▄▆▅▆▅▂▇▇
wandb:             test_auroc ▅█▅▅▅▅▅▅▅▅▅▅▃▅▄▅▄▄▄▄▄▄▅▄▃▄▁▇▅▃▃▃▅▇▂▁▅▄▃▄
wandb: test_balanced_accuracy ▄▄▆▄▄▇▃▅▅█▇▅▇▆▅▆▅▅▅▃▄▂▂▇▄▄▄▃▄▆▂▄▅▅▁▃▇▆▄▅
wandb:         test_precision ██▅█▃▄▁▂▅█▂▃▃▇▃▄▁▁█▁▆▆▄▂▁▂▁▇▅█▇▇▅▅▄▆▅▅▄▆
wandb:            test_recall ███▃▂▂▃▃▄█▃▆▃▃█▆█▁▄▃▆▄█▄▇▁▄▇▇▆▅▇▆▄▆▂▆▆▆▇
wandb:            train_auroc ▁▂▁▁▁▂▂▂▃▂▃▃▄▃▂▃▂▅▂▂▄▃▂▃▂▄▅▆▄▆▇▇▇██▆▇▇▇█
wandb:             train_loss █▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▂▃▃▃▂▂▂▂▂▂▂▂▂▁
wandb:           val_accuracy ███▄▇▆▂▃█▇▄▆▄▄▆▆███▁▃▆▇▄█▁▆▅▇▇▆▃▅▇▅▆▆▂▆▇
wandb:              val_auroc ▇████▇▆▆▇▆▃▅▆▄▅█▇▇▇▅▅▅█▆▅▆▇▇█▅▂▆▄▁▆▇▇▆▆▅
wandb:  val_balanced_accuracy ▅█▅▆▆▆▆▆▅▅▅▅▄▄▄▅▄▆▆▅▅▄▆▅▆▅▁▆▅▆▂▃▁▅▄▆▇▆▅▆
wandb:               val_loss ▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▃▁▁▁▁▂▁█
wandb:          val_precision ██▇██▄▂▆▃▆▂▄▄▄▄▆██▁▅▇▄█▃▆▁██▁▇▇▃▅█▆▆▆▂▆▇
wandb:             val_recall ███▇█▅▆▄█▅▄▄█▅▇█▁▅▄█▄▁▁▆▆▂▅█▇▅▃██▅▆▆▆▇▅▆
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.68354
wandb:             test_auroc 0.51695
wandb: test_balanced_accuracy 0.5072
wandb:         test_precision 0.68354
wandb:            test_recall 0.68354
wandb:            train_auroc 0.99564
wandb:             train_loss 0.07546
wandb:           val_accuracy 0.6875
wandb:              val_auroc 0.47656
wandb:  val_balanced_accuracy 0.5
wandb:               val_loss 6.58791
wandb:          val_precision 0.6875
wandb:             val_recall 0.6875
wandb: 
wandb: 🚀 View run resnet50_25d_norm_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc/runs/w0af3qqm
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250526_130958-w0af3qqm/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250526_142001-5z8zfg3e
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet50_25d_norm_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc/runs/5z8zfg3e
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 213, 1: 70
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 59, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:          test_accuracy ██▁█▂▃▇▃█▂▁█▃▃█▅▅▇▂▆▅▃▄▅▆▅▅▄▆▇▅▄▃▅▆▆▆▇▅▆
wandb:             test_auroc ▃▄▄▄▄▄▆▆▅▅▅▅▆▆▅▆▆▆▆▇▇▆▅▆▅▆▃▇▂▅▄▅▁▆▆▆▄█▆▆
wandb: test_balanced_accuracy ▄▄▄▄▄▄▃▆▃▆▄▅▅▄▄▅▅▄▆▅▃▄▃▃▄▆▅▂▃▄▅▁▇▅▆▂▇█▄▆
wandb:         test_precision ▁██▂▃▃▇▄▂█▄▅▁█▃█▇▅▅▇▆█▃▄▄▄▆▇▄▇▄▅▃▅▆▆▆▆▅▆
wandb:            test_recall ▁██▁█▃▂▇▃██▄▅▁█▃▄█▇▅▇▂▆█▅▅▄▅▅▄▄▅▄▃▃▅▆▆▆▆
wandb:            train_auroc ▁▂▂▂▂▂▂▂▂▃▂▂▃▃▂▃▄▄▄▄▄▅▄▅▅▇▇▆▇█▆█▇▇▇▇▇██▅
wandb:             train_loss █▄▄▄▄▄▄▄▄▄▄▄▃▄▄▄▃▃▃▃▃▃▃▃▃▃▃▂▃▂▂▃▂▂▂▂▂▁▂▃
wandb:           val_accuracy ▁███▁▂█▂▅██▆▂█▃█▁█▅▇▅▅▂█▅▅▄▅▅▄█▅▃▃▃▆▅▆█▆
wandb:              val_auroc ▇▆▃▇▇██▆▇▇▇▇▇▆▆▆▇▇▅▅▄▆▄▅▃▄▃▃▃▃▃▁▃▂▃▅▃▄▅▄
wandb:  val_balanced_accuracy ▄▄▄▄▄▅▅▇▄█▄▅▇█▄▆▇▄▃▂▄▄▄▅▄▂▃▄▁▄▄▂▁▁▁▃▅▄▆▄
wandb:               val_loss ▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▂▂▃▁▂▆▂▄▃▄▃▃▃▄█▂
wandb:          val_precision ▁█████▅▂██▃▇▁█▄▇█▇▅▅▂▇█▄▄▄▅▄▇▇▅▃▃▃▂██▆▇▆
wandb:             val_recall ███▁█▂▅▆█▆█▃▇█▁▄▅▇█▇▇█▄▅▄▄▅▅▄▃▃▃▃▂▆██▇█▆
wandb: 
wandb: Run summary:
wandb:          test_accuracy 0.64557
wandb:             test_auroc 0.54153
wandb: test_balanced_accuracy 0.54788
wandb:         test_precision 0.64557
wandb:            test_recall 0.64557
wandb:            train_auroc 0.86613
wandb:             train_loss 0.48884
wandb:           val_accuracy 0.59375
wandb:              val_auroc 0.4375
wandb:  val_balanced_accuracy 0.47917
wandb:               val_loss 1.04613
wandb:          val_precision 0.59375
wandb:             val_recall 0.59375
wandb: 
wandb: 🚀 View run resnet50_25d_norm_107_160_fold1 at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc/runs/5z8zfg3e
wandb: ⭐️ View project at: https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250526_142001-5z8zfg3e/logs
wandb: Tracking run with wandb version 0.19.11
wandb: Run data is saved locally in /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/wandb/run-20250526_152019-qz4omop1
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet50_25d_norm_107_160_fold1
wandb: ⭐️ View project at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc
wandb: 🚀 View run at https://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc/runs/qz4omop1
/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py:195: UserWarning: Experiment logs directory /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_ exists and is not empty. Previous log files in this directory will be deleted when the new ones are saved!
  rank_zero_warn(
...model pipeline for data fold 1 has run!
Saving execution datetimes to /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/execution_datetimes.json

**************************************************  Experiment 107 | Version 160 **************************************************
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
[INFO] Train dataloader 0 label distribution: 0: 213, 1: 70
[INFO] Validation dataloader 0 label distribution: 0: 24, 1: 8
[INFO] Test dataloader 0 label distribution: 0: 59, 1: 20

Running model pipeline for data fold 1...
Label column '5y' found in metadata. Available columns: ['pid', 'study_yr', 'path', 'sct_slice_num_og', 'stage', '1y', '2y', '5y', '10y', 'fup_days', 'sct_nod_err']
Error executing job with overrides: []
Traceback (most recent call last):
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 134, in run
    self.on_advance_end()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 249, in on_advance_end
    self.val_loop.run()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 122, in run
    return self.on_run_end()
           ^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 255, in on_run_end
    self.trainer._logger_connector.log_eval_end_metrics(all_logged_outputs)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 142, in log_eval_end_metrics
    self.log_metrics(metrics)
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 110, in log_metrics
    logger.save()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_utilities/core/rank_zero.py", line 41, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py", line 149, in save
    self.experiment.save()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loggers/csv_logs.py", line 64, in save
    return super().save()
           ^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py", line 228, in save
    with self._fs.open(self.metrics_file_path, "w", newline="") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/spec.py", line 1298, in open
    self.open(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/spec.py", line 1310, in open
    f = self._open(
        ^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/implementations/local.py", line 201, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/implementations/local.py", line 365, in __init__
    self._open()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/implementations/local.py", line 370, in _open
    self.f = open(self.path, mode=self.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_/metrics.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 54, in run_hyperparameter_grid_based_execution_pipeline
    run_experiment_pipeline(config)
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/slurm_files/shell_script_files/../../src/scripts/run_experiment_pipeline.py", line 165, in run_experiment_pipeline
    model_pipeline.train_model()
  File "/nas-ctm01/homes/mipaiva/pipeline_template_pl/src/modules/model/model_pipeline.py", line 68, in train_model
    self.pytorch_lightning_trainer.fit(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 66, in _call_and_handle_interrupt
    logger.finalize("failed")
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_utilities/core/rank_zero.py", line 41, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py", line 157, in finalize
    self.save()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_utilities/core/rank_zero.py", line 41, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py", line 149, in save
    self.experiment.save()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/pytorch_lightning/loggers/csv_logs.py", line 64, in save
    return super().save()
           ^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/lightning_fabric/loggers/csv_logs.py", line 228, in save
    with self._fs.open(self.metrics_file_path, "w", newline="") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/spec.py", line 1298, in open
    self.open(
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/spec.py", line 1310, in open
    f = self._open(
        ^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/implementations/local.py", line 201, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/implementations/local.py", line 365, in __init__
    self._open()
  File "/nas-ctm01/homes/mipaiva/.conda/envs/pipeline/lib/python3.11/site-packages/fsspec/implementations/local.py", line 370, in _open
    self.f = open(self.path, mode=self.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_107/version_160/datafold_/metrics.csv'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[1;34mwandb[0m: 
[1;34mwandb[0m: 🚀 View run [33mresnet50_25d_norm_107_160_fold1[0m at: [34mhttps://wandb.ai/maria-i-paiva-inesc-tec/comparative_study_25_norm_resize_fix_auc/runs/qz4omop1[0m
[1;34mwandb[0m: Find logs at: [1;35m../../experiment_results/experiment_107/version_160/wandb/run-20250526_152019-qz4omop1/logs[0m
srun: error: 04.ctm-deep-05: task 0: Exited with exit code 1
Finish time: 2025-05-26 16:18:30
